language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - "sudo apt-get update"
install:
  - "sudo apt-get install -y texlive-fonts-extra texlive-latex-recommended"
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
  - "pip install codecov"
# command to run tests
script: "pytest -v"
after_success:
- codecov
